# GitFlic CI pipeline for @ru-financial-tools/financemarker-mcp
# Stages: install -> typecheck -> test -> build -> publish

stages:
  - install
  - typecheck
  - test
  - build
  - publish

variables:
  NODE_ENV: 'ci'

cache:
  paths:
    - ~/.npm

install:
  stage: install
  # image: node:20
  scripts:
    - node -v || true
    - npm -v || true
    - npm ci

typecheck:
  stage: typecheck
  scripts:
    - npm run typecheck

test:
  stage: test
  scripts:
    - npm test
  artifacts:
    paths:
      - coverage

build:
  stage: build
  scripts:
    - npm run build

publish:
  stage: publish
  only:
    - tags
  scripts:
    - if [ -z "${NPM_TOKEN}" ]; then echo "NPM_TOKEN is not set; skipping publish" >&2; exit 1; fi
    - npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
    - npm publish --provenance --access public

# Данный файл - шаблонная конфигурация CI/CD конвейера. Он может быть изменен по Вашему усмотрению.
# Некоторые шаблоны требуют предварительной настройки перед запуском.
#
# Подробнее о синтаксисе можно узнать в документации:
# https://docs.gitflic.ru/cicd/gitflic-ci-yaml

image: ubuntu:latest

variables:
  TEST_1_SUCCESS: "true"
  TEST_2_SUCCESS: "true"

before_script:
  - echo "Скрипт до основных инструкций (в каждой задаче)"

stages:
  - test
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Сборка проекта"
    - echo "Собранный проект" > build.txt
  artifacts:
    paths: build.txt

test1:
  stage: test
  script:
    - echo "Первый набор тестов"
    - echo $TEST_1_SUCCESS

test2:
  stage: test
  script:
    - echo "Второй набор тестов"
    - echo $TEST_2_SUCCESS

deploy:
  stage: deploy
  script:
    - echo $(cat build.txt)
    - echo "Развертывание проекта"
  needs:
    - build
  rules:
    - if: $TEST_1_SUCCESS == "true" && $TEST_2_SUCCESS == "true"

after_script:
  - echo "Скрипт после основных инструкций (в каждой задаче)"
